[package]
name = "model-fold"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
maplit = "1.0.2"
string-interner = "0.13.0"
nohash-hasher = "0.2.0"